### ISSUE TITLE
 saxpy/saxpy.cu 中 kernel 执行时间测量方法有误

### ISSUE THREAD

**Issue by zxdfcv** [BienBoy/CS149-asst3#1]
查看文档的 readme，有这样一段话：
``` cpp
double startTime = CycleTimer::currentSeconds();
saxpy_kernel<<<blocks, threadsPerBlock>>>(N, alpha, device_x, device_y, device_result);
double endTime = CycleTimer::currentSeconds();
```
> You'll measure a kernel execution time that seems amazingly fast! (Because you are only timing the cost of the API call itself, not the cost of actually executing the resulting computation on the GPU.

而作者在 
saxpy/saxpy.cu 中 的实现
``` cpp
    double computeStartTime = CycleTimer::currentSeconds();
    saxpy_kernel<<<blocks, threadsPerBlock>>>(N, alpha, device_x, device_y, device_result);
    cudaDeviceSynchronize();
    double computeEndTime = CycleTimer::currentSeconds();
``` 
使用了相同的办法，由于 CUDA kernel 执行是异步的，需要在 `kernel` 执行后加同步操作 `cudaDeviceSynchronize()`。
这是一个博主的文章，个人觉得写的很准确：https://face2ai.com/CUDA-F-2-2-%E6%A0%B8%E5%87%BD%E6%95%B0%E8%AE%A1%E6%97%B6/

**Comment by BienBoy** [comment]
我检查了一下 saxpy/saxpy.cu，调用 kernel 后有进行同步，能否指明具体哪几行有问题？

**Comment by BienBoy** [comment]
> 查看文档的 readme，有这样一段话：
> 
> ```c++
> double startTime = CycleTimer::currentSeconds();
> saxpy_kernel<<<blocks, threadsPerBlock>>>(N, alpha, device_x, device_y, device_result);
> double endTime = CycleTimer::currentSeconds();
> ```
> 
> > You'll measure a kernel execution time that seems amazingly fast! (Because you are only timing the cost of the API call itself, not the cost of actually executing the resulting computation on the GPU.
> 
> 而作者在 saxpy/saxpy.cu 中 的实现
> 
> ```c++
>     double computeStartTime = CycleTimer::currentSeconds();
>     saxpy_kernel<<<blocks, threadsPerBlock>>>(N, alpha, device_x, device_y, device_result);
>     cudaDeviceSynchronize();
>     double computeEndTime = CycleTimer::currentSeconds();
> ```
> 
> 使用了相同的办法，由于 CUDA kernel 执行是异步的，需要在 `kernel` 执行后加同步操作 `cudaDeviceSynchronize()`。 这是一个博主的文章，个人觉得写的很准确：https://face2ai.com/CUDA-F-2-2-%E6%A0%B8%E5%87%BD%E6%95%B0%E8%AE%A1%E6%97%B6/

我检查了一下 saxpy/saxpy.cu，调用 kernel 后有进行同步，能否指明具体哪几行有问题？

**Comment by zxdfcv** [comment]
哦那我可能看错了，把 issue 关了吧，不好意思啦
